In [1]:
# 라이브러리를 임포트
import numpy as np

# 행렬을 생성
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# 행렬을 Transpose
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transpose는 선형대수학에서 자주 사용하는 연산입니다.<br>
이 연산은 행과 열의 인덱스를 바꿉니다.<br>
선형대수학 수업과는 달리, 벡터는 단지 값의 모음이기 때문에 transpose할 수 없습니다.<br>
하지만, 대괄호를 두 번 사용하면 벡터의 transpose가 가능합니다.

In [2]:
# transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [3]:
# transpose row-vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Transpose는 배열의 차원을 바꾸는 것이므로 1차원 배열에는 영향을 주지 않습니다.<br>
T메서드  대신 transpose메서드를 사용해도 됩니다.

In [4]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transpose 메서드는 튜플로 바꿀 차원을 직접 지정하는 것이 가능합니다.

In [20]:
# 2 x 3 x 2 행렬을 생성
matrix = np.array([[[1, 2],
                   [3, 4],
                   [5, 6]],
                   
                   [[7, 8],
                   [9, 10],
                   [11, 12]]])

# 두 번째와 세 번째 차원을 바꾸어 2 x 2 x 3 행렬로 만듭니다
matrix.transpose((0,2,1))

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])