In [1]:
# 라이브러리 임포트
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 행렬을 펼칩니다.
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

flatten은 행렬을 1차원 배열로 변환하는 간단한 메서드입니다.<br>
reshape 메서드를 사용해 행 백터를 만들 수도 있습니다.

In [2]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

reshape 메서드는 넘파이 배열의 view(기존 객체)를 반환하지만 flatten 메서드는 새로운 배열을 생성합니다.

In [3]:
vector_reshaped = matrix.reshape(-1)
vector_flattened = matrix.flatten()

# (0, 0) 위치의 원소를 변경
matrix[0][0] = -1

# 배열의 view는 원본 배열의 변경 사항을 반영합니다.
vector_reshaped

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [4]:
# flatten 메서드는 새로운 배열이므로 변경사항이 적용되지 않습니다.
vector_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])