In [1]:
# 라이브러리 임포트
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, -1, 3,],
                  [1, 1, 6],
                  [3, 8, 9]])

# 고윳값과 고유벡터를 계산합니다.
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# 고윳값을 확인합니다.
eigenvalues
                   
                   
                   

array([13.55075847,  0.74003145, -3.29078992])

In [2]:
# 고유 벡터를 확인합니다.
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

고유벡터는 머신러닝 라이브러리에서 널리 사용됩니다.<br>
행렬 A로 표현되는 선형 변환을 적용할 때 고유벡터는 스케일만 바뀌는 벡터입니다.(방향은 바뀌지 않습니다.)<br>
공식으로 나타내면 다음과 같습니다.<br>
Av = λv<br>
A가 정방행렬일 때 λ는 고윳값, v는 고유벡터입니다. 넘파이 선형대수 모듈에서 eig함수는 정방행렬의 고윳값과 고유벡터를 계산할 수 있습니다.

대칭행렬일 경우 linalg.eigh 함수를 사용하면 고윳값과 고유벡터를 더 빠르게 계산합니다.<br>
이 함수는 입력값이 대칭행렬인지 <span style = "color : red">검사하지 않습니다.</span>

In [5]:
# 대칭행렬을 생성합니다.
matrix = np.array([[1, -1, 3,],
                  [-1, 1, 6],
                  [3, 6, 9]])

# 고윳값과 고유벡터를 계산합니다.
eigenvalues, eigenvectors = np.linalg.eigh(matrix)

# 고윳값 출력
eigenvalues


array([-3.47535395,  1.84536862, 12.62998534])

In [6]:
# 고유벡터 출력
eigenvectors

array([[-0.48107069, -0.85602522,  0.18918723],
       [-0.73926367,  0.51210152,  0.43731139],
       [ 0.47123265, -0.07051844,  0.87918538]])

In [8]:
# 만약 대칭행렬이 아니라면?
matrix = np.array([[1, -1, 3,],
                  [1, 1, 6],
                  [3, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eigh(matrix)

# 고윳값과 고유벡터 출력 - 그냥 출력됨
eigenvalues, eigenvectors

(array([-4.06068011,  0.42052872, 14.64015139]),
 array([[-0.15814655,  0.96247406, -0.22052969],
        [-0.82541908, -0.25143572, -0.5054339 ],
        [ 0.54191606, -0.10209679, -0.83420815]]))