In [1]:
# 라이브러리 임포트
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 4],
                   [2, 5]])

# 역행렬을 계산합니다.
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [2]:
# 행렬과 역행렬을 곱합니다.
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

pinv 함수를 사용하면 정방행렬이 아닌 행렬의 역행렬을 계산할 수 있습니다. 이를 유사 역행렬(pseudo-inverse matrix)이라고 부릅니다.

In [3]:
matrix = np.array([[1, 4, 7],
                   [2, 5, 8]])

# 유사 역행렬을 계산합니다.
np.linalg.pinv(matrix)

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])