In [93]:
# 라이브러리 임포트
import numpy as np

# 초깃값을 지정합니다. -> 난수의 값을 고정시켜주는 역할을 합니다.
np.random.seed(0) 

# 0.0과 1.0 사이에서 세 개의 실수 난수를 생성합니다.
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [94]:
# 1과 10 사이에서 세 개의 정수 난수를 생성합니다.
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [95]:
# 평균이 0.0이고 표준편차가 1.0인 정규분포에서 세 개의 수를 뽑습니다.
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [96]:
# 평균이 0.0이고 스케일이 1.0인 로지스틱 분포에서 세 개의 수를 뽑습니다.
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [97]:
# 1.0보다 크거나 같고 2.0보다 작은 세 개의 수를 뽑습니다.
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

동일한 결과를 얻으려면 같은 난수를 생성해야 합니다. 이렇게 하려면 의사 난수 생성기의 '초깃값'을 설정합니다.<br>
동일한 초깃값을 가진 난수 생성은 항상 <span style = "color : red">같은 결과를 출력합니다.</span>

In [154]:
# 0.0(포함)과 1.0 사이에서 세 개의 실수 난수를 생성합니다.
# np.random.random((2, 3)), np.random.smaple((2, 3)),
# np.random.uniform(0.0, 1.0, (2,3))과 동일합니다.
np.random.random_sample((2, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [168]:
np.random.random((2, 3)) , np.random.sample((2, 3)), np.random.uniform(0.0, 1.0, (2, 3))

(array([[0.86385561, 0.11753186, 0.51737911],
        [0.13206811, 0.71685968, 0.3960597 ]]),
 array([[0.56542131, 0.18327984, 0.14484776],
        [0.48805628, 0.35561274, 0.94043195]]),
 array([[0.76532525, 0.74866362, 0.90371974],
        [0.08342244, 0.55219247, 0.58447607]]))

이와 비슷한 rand 함수는 크기를 튜플이 아니라 개별적인 매개변수로 전달합니다.

In [188]:
# np.random.random_sample((2, 3))과 동일합니다.
np.random.rand(2, 3)

array([[0.75677864, 0.63606106, 0.24002027],
       [0.16053882, 0.79639147, 0.9591666 ]])

randint 함수는 최솟값을 포함하고 최댓값은 포함하지 않는 정수 난수를 생성합니다.

In [190]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

standard_normal 함수를 사용해 평균이 0.0이고 표준편차가 1.0인 정규분포의 난수를 생성할 수 있습니다.

In [192]:
# np.random.normal(0.0, 1.0, (2, 3))과 동일합니다.
np.random.standard_normal((2, 3))

array([[ 2.3039167 , -1.06001582, -0.1359497 ],
       [ 1.13689136,  0.09772497,  0.58295368]])

이와 비슷한 rand 함수는 크기를 튜플이 아니라 개별적인 매개변수로 전달합니다.

In [193]:
# np.random.normal(0.0, 1.0, (2, 3))과 동일합니다.
np.random.randn(2, 3)

array([[-0.39944903,  0.37005589, -1.30652685],
       [ 1.65813068, -0.11816405, -0.6801782 ]])

choice 함수는 배열의 원소 중에서 랜덤하게 지정된 횟수만큼 샘플을 만듭니다.<br>
또는 0 ~ 정수 사이의 원소 중에서 랜덤하게 샘플을 선택합니다.

In [194]:
# 0 ~ 2 사이의 정수 중 랜덤하게 5번을 뽑습니다.
# np.random.choice(3, 5)와 동일합니다.
np.random.choice([0, 1, 2], 5)

array([2, 1, 0, 0, 1])

shuffle 함수는 입력된 배열을 섞습니다.

In [205]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([0, 1, 2, 3, 4, 5])
np.random.shuffle(a)
a

array([0, 2, 5, 1, 3, 4])

permutation 함수는 입력된 배열의 복사본을 만들어 섞은 후 반환합니다.<br>
정수를 입력하면 0에서부터 정수까지 섞은 후 반환합니다.

In [206]:
# 입력 배열은 변경되지 않습니다.
np.random.permutation(b)

array([0, 2, 1, 5, 3, 4])

In [207]:
b

array([0, 1, 2, 3, 4, 5])

In [208]:
np.random.permutation(5)

array([1, 4, 0, 2, 3])