In [3]:
#import library
import numpy as np

#make matrix
matrix = np.array([[1, 2],
                  [1, 2],
                   [1, 2]])
print(matrix)
type(matrix)

[[1 2]
 [1 2]
 [1 2]]


numpy.ndarray

# .mat는 권장되지 않는다.  
## => array가 numpy의 표준 데이터 구조이기 때문이며, 대부분의 numpy함수가 matrix object가 아닌 array를 반환하기 때문!

In [4]:
#numpy method .mat 권장되지는 않는다.
matrix_object = np.mat([[1, 2],
                  [1, 2],
                   [1, 2]])
print(matrix_object)
type(matrix_object)

[[1 2]
 [1 2]
 [1 2]]


numpy.matrix

In [5]:
#zeros는 0행렬을, ones는 모든 성분이 1인 행렬을 만든다
zero_matrix = np.zeros((3,2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
one_matrix = np.ones((3,2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# 특정 값으로 채운 배열을 만들려면 full 함수를 사용하자.
## zeros를 만들고 +n을 해도 가능하긴하나, 복잡


In [7]:
seven_matrix = np.zeros((3,2)) + 7
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [8]:
seven_matrix = np.full((3,2), 7) 
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])