In [3]:
# 라이브러리 임포트
import numpy as np

# 행렬을 생성
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 가장 큰 원소를 반환
np.max(matrix)

1

In [4]:
# 가장 작은 원소를 반환
np.min(matrix)

1

axis 매개변수를 사용해 특정 축을 따라 연산을 수행할 수 있다.

In [5]:
# 각 열에서 최댓값을 반환
np.max(matrix, axis=0)

array([7, 8, 9])

In [6]:
# 각 행에서 최댓값을 반환
np.max(matrix, axis=1)

array([3, 6, 9])

keepdims 매개변수를 True로 지정하면 원본 배열의 차원과 동일한 결과를 만든다.<br>(원본의 형태를 유지하며 결과를 출력한다)<br>
원본 배열과 안전하게 브로드캐스팅 연산이 가능하다.

In [8]:
# 이전 예와 달리 (3, 1) 크기의 열 벡터가 생성됨
vector_column = np.max(matrix, axis=1, keepdims=True)
vector_column

array([[3],
       [6],
       [9]])

In [9]:
# 열 벡터이므로 브로드캐스팅을 이용해 각 행의 최댓값을 뺄 수 있다
matrix - vector_column

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])