1. Create the following vector variables

In [4]:
import numpy as np
import math

# a
v = np.array([[3, 0, 2.1, 4, 0.2]])
v

array([[3. , 0. , 2.1, 4. , 0.2]])

In [26]:
# b
u = np.array([[np.exp(-1), np.exp(0), np.exp(1), np.exp(2), np.exp(3)]]).T
u

array([[ 0.36787944],
       [ 1.        ],
       [ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [9]:
# c
w = np.array(range(-4, 1))
w

array([-4, -3, -2, -1,  0])

In [11]:
# d
m = np.array(range(0, 11, 2))
m

array([ 0,  2,  4,  6,  8, 10])

In [27]:
# e
s = np.linspace(2, 0, 21).T
s

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. , 0.9, 0.8,
       0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [24]:
# f
