## 1. Create the following vector variables

In [85]:
import numpy as np
import math
from math import pi

# a
v = np.array([3, 0, 2.1, 4, 0.2])
v

array([3. , 0. , 2.1, 4. , 0.2])

In [86]:
# b
u = np.array([[np.exp(-1), np.exp(0), np.exp(1), np.exp(2), np.exp(3)]]).T
u

array([[ 0.36787944],
       [ 1.        ],
       [ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [87]:
# c
w = np.array(range(-4, 1))
w

array([-4, -3, -2, -1,  0])

In [88]:
# d
m = np.array(range(0, 11, 2))
m

array([ 0,  2,  4,  6,  8, 10])

In [89]:
# e
k = np.linspace(2, 0, 21)
s = np.array([k]).T
s

array([[2. ],
       [1.9],
       [1.8],
       [1.7],
       [1.6],
       [1.5],
       [1.4],
       [1.3],
       [1.2],
       [1.1],
       [1. ],
       [0.9],
       [0.8],
       [0.7],
       [0.6],
       [0.5],
       [0.4],
       [0.3],
       [0.2],
       [0.1],
       [0. ]])

In [90]:
# f
l = np.linspace(0, 2*pi, 100)
t = np.array([l]).T
t

array([[0.        ],
       [0.06346652],
       [0.12693304],
       [0.19039955],
       [0.25386607],
       [0.31733259],
       [0.38079911],
       [0.44426563],
       [0.50773215],
       [0.57119866],
       [0.63466518],
       [0.6981317 ],
       [0.76159822],
       [0.82506474],
       [0.88853126],
       [0.95199777],
       [1.01546429],
       [1.07893081],
       [1.14239733],
       [1.20586385],
       [1.26933037],
       [1.33279688],
       [1.3962634 ],
       [1.45972992],
       [1.52319644],
       [1.58666296],
       [1.65012947],
       [1.71359599],
       [1.77706251],
       [1.84052903],
       [1.90399555],
       [1.96746207],
       [2.03092858],
       [2.0943951 ],
       [2.15786162],
       [2.22132814],
       [2.28479466],
       [2.34826118],
       [2.41172769],
       [2.47519421],
       [2.53866073],
       [2.60212725],
       [2.66559377],
       [2.72906028],
       [2.7925268 ],
       [2.85599332],
       [2.91945984],
       [2.982

## 2. Create the following matrix variables

In [91]:
# a
mat_a = np.eye(3, dtype = int)
mat_b = np.array([[0, -2, 0],
              [-2, 0, -2],
              [0, -2, 0]], dtype = int)
A = mat_a + mat_b
A

array([[ 1, -2,  0],
       [-2,  1, -2],
       [ 0, -2,  1]])

In [92]:
# b
zero_matrix = np.zeros((9, 9), dtype = int)
zero_matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [106]:
# c
full_three = np.full((9, 9), 3, dtype = int)
full_three

array([[3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [94]:
# d
C = np.full((9, 9), 9, dtype = int) - 9 * np.eye(9, dtype = int)
C

array([[0, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 0, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 0, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 0, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 0, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 0, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 0, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 0, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 0]])

In [95]:
# e
d = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
D = np.diag(d)
D

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [96]:
# f
zeros = np.zeros((9, 5), dtype = int)
f = np.arange(1, 10)
zeros + np.array([f]).T


array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

## 3. Perform the following operations using the variables created from the problems 1&2

In [97]:
# a
# range(np.size(v))
for i in range(np.size(v)):
    v[i] = math.sqrt(v[i])
v2 = np.exp(v)
v2

array([5.65223367, 1.        , 4.25943991, 7.3890561 , 1.56394832])

In [98]:
# b
log_u = np.log(u)
log_u

array([[-1.],
       [ 0.],
       [ 1.],
       [ 2.],
       [ 3.]])

In [99]:
# c
W = np.abs(w) + [4]
W

array([8, 7, 6, 5, 4])

In [100]:
# d
T = np.sin(t)
T

array([[ 0.00000000e+00],
       [ 6.34239197e-02],
       [ 1.26592454e-01],
       [ 1.89251244e-01],
       [ 2.51147987e-01],
       [ 3.12033446e-01],
       [ 3.71662456e-01],
       [ 4.29794912e-01],
       [ 4.86196736e-01],
       [ 5.40640817e-01],
       [ 5.92907929e-01],
       [ 6.42787610e-01],
       [ 6.90079011e-01],
       [ 7.34591709e-01],
       [ 7.76146464e-01],
       [ 8.14575952e-01],
       [ 8.49725430e-01],
       [ 8.81453363e-01],
       [ 9.09631995e-01],
       [ 9.34147860e-01],
       [ 9.54902241e-01],
       [ 9.71811568e-01],
       [ 9.84807753e-01],
       [ 9.93838464e-01],
       [ 9.98867339e-01],
       [ 9.99874128e-01],
       [ 9.96854776e-01],
       [ 9.89821442e-01],
       [ 9.78802446e-01],
       [ 9.63842159e-01],
       [ 9.45000819e-01],
       [ 9.22354294e-01],
       [ 8.95993774e-01],
       [ 8.66025404e-01],
       [ 8.32569855e-01],
       [ 7.95761841e-01],
       [ 7.55749574e-01],
       [ 7.12694171e-01],
       [ 6.6

In [101]:
# e
np.flip(A, axis= 0)

array([[ 0, -2,  1],
       [-2,  1, -2],
       [ 1, -2,  0]])

In [108]:
# f
full_three = np.full((9, 9), 3, dtype = int)
full_three[1:2] += [-2]
full_three

array([[3, 3, 3, 3, 3, 3, 3, 3, 3],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [121]:
# g
d = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])
D = np.diag(d)
D_del = np.delete(D, 0, 0)
D_del

array([[0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [122]:
# h
C2 = C[0:2, 0:2]
C2

array([[0, 9],
       [9, 0]])

In [128]:
# i
zeros = np.zeros((9, 5), dtype = int)
f = np.arange(1, 10)
F = zeros + np.array([f]).T
f_flipped = np.flip(np.array([f]).T, axis= 0)
# f_flipped
F[:, 0:1] = f_flipped
F

array([[9, 1, 1, 1, 1],
       [8, 2, 2, 2, 2],
       [7, 3, 3, 3, 3],
       [6, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [4, 6, 6, 6, 6],
       [3, 7, 7, 7, 7],
       [2, 8, 8, 8, 8],
       [1, 9, 9, 9, 9]])