In [1]:
# 라이브러리 임포트
import numpy as np

# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

# 대각원소를 반환합니다.
matrix.diagonal()

array([1, 4, 9])

넘파이의 diagonal 메서드를 사용하여 대각원소를 손쉽게 얻을 수 있습니다.<br>
offset 매개변수를 사용하면 주 대각선에서 벗어난 대각원소를 얻을 수 있습니다.

In [2]:
# 주 대각선 하나 위의 대각원소를 반환합니다.
matrix.diagonal(offset = 1)

array([2, 6])

In [3]:
# 주 대각선 하나 아래의 대각원소를 반환합니다.
matrix.diagonal(offset = -1)

array([2, 8])

diagonal 메서드는 원본 배열의 뷰를 반환합니다.<br>
반환된 배열의 원소를 바꾸려면 배열을 복사해 사용해야 합니다.

In [5]:
# 반환된 배열을 변경하려면 복사
a = matrix.diagonal().copy()
b = matrix.diagonal()

a[0] = -1
a

array([-1,  4,  9])

'''
ValueError: assignment destination is read-only

b[0] = 2
b
'''

넘파이 diag함수도 대각원소를 추출합니다.<br>
이 함수는 1차원 배열이 주어졌을 때 역으로 대각행렬을 만듭니다.

In [8]:
a = np.diag(matrix)
print(a)

[1 4 9]


In [9]:
# 1차원 배열이 주어지면 2차원 대각행렬을 만듭니다.
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])