In [1]:
#import library
import numpy as np
from scipy import sparse

In [2]:
#make matrix
matrix = np.array([[0,0],
                 [0,1],
                 [3,0]])

In [3]:
#make CSR matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [4]:
#print sparse matrix
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


### 0이 아닌 성분의 위치와 값을 저장한다.

In [5]:
#큰 행렬을 만들어봅시다.
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
#CSR행렬 생성
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [7]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


행렬이 커질 경우 간결하게 정보를 조회할 수 있는 장점이 있다.<br>
그리고 0을 추가해도 sparse matrix의 크기는 변하지 않는다.<br><br>
원소의 행과 열의 인덱스를 직접 지정해 sparse matrix를 생성하는 것도 가능하다.

In [8]:
#(data, (row_index, col_index))로 구성된 튜플을 전달합니다.
# shape 매개변수에서 0을 포함한 행렬의 전체 크기를 지정합니다.
matrix_sparse2 = sparse.csr_matrix(([1, 3], ([1, 2], [1, 0])), shape = (3, 10))

print(matrix_sparse2)

  (1, 1)	1
  (2, 0)	3


sparse matrix를 dense array로 전환하려면 toarray 메서드를 사용하면 된다.

In [9]:
print(matrix_sparse2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [10]:
#todense 메서드는 np.matrix객체를 반환한다.
matrix_sparse2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)