In [1]:
# 라이브러리 임포트
import numpy as np

# 행 벡터를 생성
vector = np.array([1, 2, 3, 4, 5, 6])

# 행렬 생성
matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# vector의 세 번째 원소를 선택
vector[2]

3

In [2]:
# matrix의 두 번째 행, 두 번째 열의 원소를 선택
matrix[1,1]

5

In [3]:
# 벡터에 있는 모든 원소를 선택
vector[:]

array([1, 2, 3, 4, 5, 6])

In [4]:
# 세 번째 원소를 포함하며 그 이전의 모든 원소 선택
vector[:3]


array([1, 2, 3])

In [5]:
# 세 번째 이후의 모든 원소를 선택
vector[3:]

array([4, 5, 6])

In [6]:
# 마지막 원소 선택
vector[-1]

6

In [7]:
# 행렬에서 첫 번째 두 행과 모든 열을 선택
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 모든 행과 두 번째 열을 선택
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

In [9]:
# 첫 번째 행과 세 번째 행을 선택
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [10]:
# (0.1), (2,0)위치의 원소를 선택
matrix[[0, 2], [1, 0]]

array([2, 7])

In [11]:
# matrix의 각 원소에 비교 연산자를 적용하기
mask = matrix > 5

mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [12]:
# 불리언 마스크 배열을 사용해 원소를 선택
matrix[mask]

array([6, 7, 8, 9])

In [13]:
# mask의 데이터 타입은 뭘까 array? -> ndarray!
type(mask)

numpy.ndarray