In [3]:
# 라이브러리 임포트
import numpy as np

# 행렬을 생성
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 100을 더하는 함수를 생성
add_100 = lambda i: i+ 100

# 벡터화된 함수를 생성
vectorized_add_100 = np.vectorize(add_100)

# 행렬의 모든 원소에 함수를 적용
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

브로드캐스팅은 배열에 차원을 추가하거나 반복해서 배열의 크기를 맞춥니다.

In [5]:
# (3, 3) 크기 행렬에 (1, 3) 크기의 벡터를 더하면
# (1, 3) 크기가 된 다음 다음 행을 따라 반복됩니다.
matrix + [100, 100, 100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [6]:
# (3, 3) 크기 행렬에 (3, 1) 크기의 벡터를 더하면 열을 따라 반복됩니다.
matrix + [[100], [100], [100]]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])