In [1]:
# 라이브러리를 임포트
import numpy as np

# 4 x 3 행렬을 생성
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# 2 x 6 행렬로 크기를 변경
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

reshape 함수는 데이터를 동일하게 유지하면서 배열의 구조를 변경해 행과 열의 수를 다르게 할 수 있습니다.<br>
새로운 행렬은 원래 행렬과 원소의 수가 같아야 하며, size 속성을 사용해 원소 수를 확인할 수 있습니다.

In [2]:
matrix.size

12

reshape 함수에 사용 가능한 매개변수 -1은 가능한 많이라는 뜻으로 사용됩니다.<br>
reshape(1, -1)은 행 하나에 열은 가능한 많게라는 뜻.

In [3]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

reshape에 정수 하나를 입력하면 그 길이의 1차원 배열을 반환합니다.(정수 = 원래 행렬의 원소 수)<br>
혹은 reshape에 -1을 입력하면 1차원 배열로 바꾸어줍니다.

In [6]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

ravel 메서드도 이와 동일한 기능을 합니다.

In [8]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])